# set scroll history to 100,000 lines
set-option -g history-limit 100000

# get links working
set -ga terminal-features "*:hyperlinks"

# Remap default action prefix
unbind C-b
set-option -g prefix C-a 
set -s escape-time 3
set-option -g repeat-time 0
set-option -g focus-events on

# use fish shell
set-option -g default-shell /usr/bin/fish

set -g mouse on 

# color 
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',*:RGB' # Enable 24 bit true colors
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm' # Enable undercurl
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # Enable undercurl with proper colors
set -sa terminal-overrides ',*:S'

set -g set-titles on
set -g set-titles-string "[#S]->#W"

# Quick refresh of tmux config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded config 🚀"

# windows index start at 1
set -g base-index 1
setw -g pane-base-index 1 
set -g renumber-windows on

# Split window bindings
unbind %
bind | split-window -h -c "#{pane_current_path}"        # vertical split, open in current directory
bind '"' split-window -c "#{pane_current_path}"         # horizontal split, open in current directory
bind c new-window -c "#{pane_current_path}"             # opens new window in current directory
bind -r h select-pane -L                                # select pane on left
bind -r j select-pane -D                                # select pane on bottom
bind -r k select-pane -U                                # select pane on top
bind -r l select-pane -R                                # select pane on right

# Resizing pane
bind -r C-k resize-pane -U 3                            
bind -r C-j resize-pane -D 3
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

bind m resize-pane -Z                                   # Maximize pane

bind -r e kill-pane  # kill current pane without confirmation 

# Act like vim
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# tmux tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# STATUSLINE POSITION (top, bottom)
set-option -g status-position bottom 

# Avoid date/time taking up space
set -g status-right ' [#S] '
set -g status-left ' '
set -g status-right-length 0

# Base16 Gruvbox dark, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#bdae93,bg=#3c3836"

# default window title colors
set-window-option -g window-status-style "fg=#bdae93,bg=default"

# active window title colors
set-window-option -g window-status-current-style "fg=#fabd2f,bg=default"

# pane border
set-option -g pane-border-style "fg=#3c3836"
set-option -g pane-active-border-style "fg=#504945"

# message text
set-option -g message-style "fg=#d5c4a1,bg=#3c3836"

# pane number display
set-option -g display-panes-active-colour "#b8bb26"
set-option -g display-panes-colour "#fabd2f"

# clock
set-window-option -g clock-mode-colour "#b8bb26"

# copy mode highligh
set-window-option -g mode-style "fg=#bdae93,bg=#504945"

# bell
set-window-option -g window-status-bell-style "fg=#3c3836,bg=#fb4934"
